"""empty message

Revision ID: 1b7554633004
Revises: 362d488d7dd8
Create Date: 2019-08-18 17:21:02.685330

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b7554633004'
down_revision = '362d488d7dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('active_player', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'active_player')
    # ### end Alembic commands ###
