"""empty message

Revision ID: 2da0113dbaa7
Revises: 
Create Date: 2019-08-17 23:22:15.300144

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da0113dbaa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('player_one_type', sa.String(), nullable=True),
                    sa.Column('player_two_type', sa.String(), nullable=True),
                    sa.Column('game_state', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
