"""empty message

Revision ID: 362d488d7dd8
Revises: 830079dd919a
Create Date: 2019-08-18 00:56:30.031173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '362d488d7dd8'
down_revision = '830079dd919a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('player_one_type', sa.String(), nullable=True),
                    sa.Column('player_two_type', sa.String(), nullable=True),
                    sa.Column('game_state', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
