"""empty message

Revision ID: 4c956f2ceb65
Revises: 2da0113dbaa7
Create Date: 2019-08-17 23:47:54.662105

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c956f2ceb65'
down_revision = '2da0113dbaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_uuid_key', 'games', type_='unique')
    op.drop_column('games', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('games_uuid_key', 'games', ['uuid'])
    # ### end Alembic commands ###
