"""empty message

Revision ID: 830079dd919a
Revises: 4c956f2ceb65
Create Date: 2019-08-18 00:38:34.894107

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '830079dd919a'
down_revision = '4c956f2ceb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('player_one_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('player_two_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('game_state', postgresql.BYTEA(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='games_pkey')
                    )
    # ### end Alembic commands ###
